### ISSUE TITLE
Axis attributes dropped after retrieving/generating bounds

### ISSUE THREAD

**Issue by pochedls** [tomvothecoder/xcdat#78]
I noticed that if I generate or retrieve axis bounds, some of the axis information is dropped. Ideally, all of the axis information should be retained when generating bounds. 

### What are the steps to reproduce this issue?
```import xarray as xr
from xcdat import axis

fn = '/p/css03/esgf_publish/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Amon/tas/gn/v20190308/tas_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc'
ds = xr.open_dataset(fn)
print(ds.lat.units)
```
> degrees_north
```
lat_bnds = ds.axis.get_bounds("lat", generate="True")
print(ds.lat.units)
```
> AttributeError: 'DataArray' object has no attribute 'units'

**Comment by tomvothecoder** [comment]
Thanks @pochedls, happy to see you're experimenting with the code. I'll look into this, should be an easy fix.
