### ISSUE TITLE
Add Dataset and data variable wrappers to apply common operations upon opening

### ISSUE THREAD

**Issue by tomvothecoder** [tomvothecoder/xcdat#80]
### Is your feature request related to a problem? If yes, Please describe

CDAT users commonly work on a single `TransientVariable` of a dataset, which is equivalent to a single xarray `Dataset` data variable of type `DataArray`. However, an xarray data variable does not link to other data variables. This means that the extracted data variable does not have access to any existing axis bounds (also data variables).

### Describe your proposed solution

Acceptance Criteria
1. Add `open_dataset` function to open a dataset and generate bounds if they don't exist. 
   - [x] Extensible for additional operations.
   - [x] Add call to generate bounds if it doesn't exist
2. Add `open_variable` function to open a data variable with axis bounds (passed from parent Dataset). Replicates CDAT `TransientVariable`.
   - [x] Extensible for additional operations
   - [x] Add DataArray accessor to add additional attributes to DataArray class (to store bounds info)
   - [x] Show all attributes of accessor class (just use `__dict__`)
   - [x] Take into account dataset's calendar (EDIT: not needed, but keep calendar type in encoding if available)
      - I don’t think the calendar type affects the algorithm for generating a date range. Non-CF units “months since…” or “years since…” don’t factor the number of days in a month.
      - pd.date_range() generates proleptic_gregorian datetime values

### Describe alternatives solutions you've considered

- On creation of the variable (easiest for the user): tas = ds.tas
  - **Not possible because this is native xarray syntax, which requires extending via subclassing (not recommended) or xarray accessors.**
- On dataset open: ds = xcdat.load_dataset(filename) [this would embed the bounds in the relevant variables so that they are included in ds.tas]
  - **Not possible, I found Dataset data variables don't preserve custom attributes via DataArray accessors**
 
### Additional context

- Extracts some tasks for #77

**Comment by tomvothecoder** [comment]
Hey @pochedls, let me know if there are any other common operations that should be performed.

**Comment by pochedls** [comment]
@tomvothecoder - an issue that arose that inspired this ticket was that xarray does not read a pretty common time unit "months since." I'm wondering if `open_dataset` could be used to deal with issues like this (though perhaps not in the initial release)?

**Comment by tomvothecoder** [comment]
@pochedls Thanks, this ticket extracts the easier items from #77. I'll continue the conversation specific to that issue on #77.
